services:
  app:
    build: .
    container_name: school-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - npm_net

networks:
  npm_net:
    external: true
