version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
